blank_issues_enabled: true
contact_links:
- name: ğŸ™‹ğŸ¾ Question
  url: https://github.com/jollie-candy/ebscasino-roadmap/discussions/new
  about: Use this link to submit your question to GitHub Discussions.